name: Deploy & Verify

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Install forge-std
        run: |
          forge install foundry-rs/forge-std --no-commit

      - name: Check files
        run: |
          ls -R lib

      - name: Build
        run: forge build

      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          BASE_RPC: ${{ secrets.BASE_RPC }}
        run: |
          forge script script/Deploy.s.sol \
            --rpc-url "$BASE_RPC" \
            --private-key "$PRIVATE_KEY" \
            --broadcast \
            --verify \
            --etherscan-api-key "${{ secrets.BASESCAN_API_KEY }}"
