name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Prepare forge-std
        run: |
          rm -rf lib/forge-std
          mkdir -p lib
          git clone https://github.com/foundry-rs/forge-std.git lib/forge-std

      - name: Build
        run: forge build

      - name: Deploy & Verify
        env:
          PRIVATE_KEY: ${{ secrets.24db1a1eec1fbc7049802dc25a7ffc7eee30f776743dc0071028923e4d8801d3 }}
          BASE_RPC: ${{ secrets.BASE_RPC }}
          ETHERSCAN_API_KEY: ${{ secrets.CZYM52CXJG7D5W9S2T515IUHQ2TNW6R3B9 }}
        run: |
          forge script script/Deploy.s.sol \
            --rpc-url $BASE_RPC \
            --private-key $PRIVATE_KEY \
            --broadcast \
            --verify \
            --etherscan-api-key $ETHERSCAN_API_KEY
